// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post_like

import (
	"github.com/chenmingyong0423/fnote/server/internal/post_like/internal/repository"
	"github.com/chenmingyong0423/fnote/server/internal/post_like/internal/repository/dao"
	"github.com/chenmingyong0423/fnote/server/internal/post_like/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/post_like/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitPostLikeModule(mongoDB *mongo.Database) *Model {
	postLikeDao := dao.NewPostLikeDao(mongoDB)
	postLikeRepository := repository.NewPostLikeRepository(postLikeDao)
	postLikeService := service.NewPostLikeService(postLikeRepository)
	postLikeHandler := web.NewPostLikeHandler(postLikeService)
	model := &Model{
		Svc: postLikeService,
		Hdl: postLikeHandler,
	}
	return model
}

// wire.go:

var PostLikeProviders = wire.NewSet(web.NewPostLikeHandler, service.NewPostLikeService, repository.NewPostLikeRepository, dao.NewPostLikeDao, wire.Bind(new(service.IPostLikeService), new(*service.PostLikeService)), wire.Bind(new(repository.IPostLikeRepository), new(*repository.PostLikeRepository)), wire.Bind(new(dao.IPostLikeDao), new(*dao.PostLikeDao)))
