// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package message

import (
	"github.com/chenmingyong0423/fnote/server/internal/email/internal/service"
	service2 "github.com/chenmingyong0423/fnote/server/internal/message/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/message_template"
	"github.com/chenmingyong0423/fnote/server/internal/website_config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitMessageModule(emailServ service.IEmailService, messageTemplateModule *message_template.Module, websiteConfigModule *website_config.Module) *Module {
	iWebsiteConfigService := websiteConfigModule.Svc
	iMessageTemplateService := messageTemplateModule.Svc
	messageService := service2.NewMessageService(iWebsiteConfigService, emailServ, iMessageTemplateService)
	module := &Module{
		Svc: messageService,
	}
	return module
}

// wire.go:

var MessageProviders = wire.NewSet(service2.NewMessageService, wire.Bind(new(service2.IMessageService), new(*service2.MessageService)))
