// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package message

import (
	"github.com/chenmingyong0423/fnote/server/internal/email"
	"github.com/chenmingyong0423/fnote/server/internal/message/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/message_template"
	"github.com/chenmingyong0423/fnote/server/internal/website_config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitMessageModule(emailModule *email.Module, messageTemplateModule *message_template.Module, websiteConfigModule *website_config.Module) *Module {
	iWebsiteConfigService := websiteConfigModule.Svc
	iEmailService := emailModule.Svc
	iMessageTemplateService := messageTemplateModule.Svc
	messageService := service.NewMessageService(iWebsiteConfigService, iEmailService, iMessageTemplateService)
	module := &Module{
		Svc: messageService,
	}
	return module
}

// wire.go:

var MessageProviders = wire.NewSet(service.NewMessageService, wire.Bind(new(service.IMessageService), new(*service.MessageService)))
