// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package email

import (
	"github.com/chenmingyong0423/fnote/server/internal/email/internal/service"
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEmailModule(db *mongox.Database) *Module {
	emailService := service.NewEmailService()
	module := &Module{
		Svc: emailService,
	}
	return module
}

// wire.go:

var EmailProviders = wire.NewSet(service.NewEmailService, wire.Bind(new(service.IEmailService), new(*service.EmailService)))
