// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aggregate_post

import (
	service2 "github.com/chenmingyong0423/fnote/server/internal/aggregate_post/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/aggregate_post/internal/web"
	"github.com/chenmingyong0423/fnote/server/internal/post/service"
	"github.com/chenmingyong0423/fnote/server/internal/post_draft"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitAggregatePostModule(postServ service.IPostService, postDraftModel *post_draft.Model) *Model {
	iPostDraftService := postDraftModel.Svc
	aggregatePostService := service2.NewAggregatePostService(postServ, iPostDraftService)
	aggregatePostHandler := web.NewAggregatePostHandler(aggregatePostService)
	model := &Model{
		Svc: aggregatePostService,
		Hdl: aggregatePostHandler,
	}
	return model
}

// wire.go:

var AggregatePostProviders = wire.NewSet(web.NewAggregatePostHandler, service2.NewAggregatePostService, wire.Bind(new(service2.IAggregatePostService), new(*service2.AggregatePostService)))
