// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post_index

import (
	"github.com/chenmingyong0423/fnote/server/internal/category"
	"github.com/chenmingyong0423/fnote/server/internal/file"
	"github.com/chenmingyong0423/fnote/server/internal/post"
	"github.com/chenmingyong0423/fnote/server/internal/post_index/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/post_index/internal/web"
	"github.com/chenmingyong0423/fnote/server/internal/tag"
	"github.com/chenmingyong0423/fnote/server/internal/website_config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitPostIndexModule(cfgModule *website_config.Module, categoryModule *category.Module, tagModule *tag.Module, postModule *post.Module, fileModule *file.Module) *Module {
	baiduService := service.NewBaiduService()
	iWebsiteConfigService := cfgModule.Svc
	iPostService := postModule.Svc
	iFileService := fileModule.Svc
	iCategoryService := categoryModule.Svc
	iTagService := tagModule.Svc
	postIndexService := service.NewPostIndexService(baiduService, iWebsiteConfigService, iPostService, iFileService, iCategoryService, iTagService)
	postIndexHandler := web.NewPostIndexHandler(postIndexService)
	module := &Module{
		Svc: postIndexService,
		Hdl: postIndexHandler,
	}
	return module
}

// wire.go:

var PostIndexProviders = wire.NewSet(web.NewPostIndexHandler, service.NewPostIndexService, service.NewBaiduService, wire.Bind(new(service.IPostIndexService), new(*service.PostIndexService)))
