// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package visit_log

import (
	"github.com/chenmingyong0423/fnote/server/internal/visit_log/internal/repository"
	"github.com/chenmingyong0423/fnote/server/internal/visit_log/internal/repository/dao"
	"github.com/chenmingyong0423/fnote/server/internal/visit_log/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/visit_log/internal/web"
	"github.com/chenmingyong0423/go-eventbus"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitVisitLogModule(mongoDB *mongo.Database, eventBus *eventbus.EventBus) *Module {
	visitLogDao := dao.NewVisitLogDao(mongoDB)
	visitLogRepository := repository.NewVisitLogRepository(visitLogDao)
	visitLogService := service.NewVisitLogService(visitLogRepository)
	visitLogHandler := web.NewVisitLogHandler(visitLogService, eventBus)
	module := &Module{
		Svc: visitLogService,
		Hdl: visitLogHandler,
	}
	return module
}

// wire.go:

var VisitLogProviders = wire.NewSet(web.NewVisitLogHandler, service.NewVisitLogService, repository.NewVisitLogRepository, dao.NewVisitLogDao, wire.Bind(new(service.IVisitLogService), new(*service.VisitLogService)), wire.Bind(new(repository.IVisitLogRepository), new(*repository.VisitLogRepository)), wire.Bind(new(dao.IVisitLogDao), new(*dao.VisitLogDao)))
