// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package data_analysis

import (
	"github.com/chenmingyong0423/fnote/server/internal/comment"
	"github.com/chenmingyong0423/fnote/server/internal/count_stats"
	"github.com/chenmingyong0423/fnote/server/internal/data_analysis/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/data_analysis/internal/web"
	"github.com/chenmingyong0423/fnote/server/internal/post_like"
	"github.com/chenmingyong0423/fnote/server/internal/visit_log"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitDataAnalysisModule(mongoDB *mongo.Database, countStatsModule *count_stats.Module, posLikeModule *post_like.Module, commentModule *comment.Module, visitLogModule *visit_log.Module) *Module {
	iVisitLogService := visitLogModule.Svc
	iCountStatsService := countStatsModule.Svc
	iPostLikeService := posLikeModule.Svc
	iCommentService := commentModule.Svc
	ipApiService := service.NewIpApiService()
	dataAnalysisHandler := web.NewDataAnalysisHandler(iVisitLogService, iCountStatsService, iPostLikeService, iCommentService, ipApiService)
	module := &Module{
		Hdl: dataAnalysisHandler,
	}
	return module
}

// wire.go:

var DataAnalysisProviders = wire.NewSet(web.NewDataAnalysisHandler, service.NewIpApiService, wire.Bind(new(service.IIpApiService), new(*service.IpApiService)))
