// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package data_analysis

import (
	"github.com/chenmingyong0423/fnote/server/internal/comment"
	service2 "github.com/chenmingyong0423/fnote/server/internal/count_stats/service"
	service3 "github.com/chenmingyong0423/fnote/server/internal/data_analysis/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/data_analysis/internal/web"
	"github.com/chenmingyong0423/fnote/server/internal/post_like"
	"github.com/chenmingyong0423/fnote/server/internal/visit_log/service"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitDataAnalysisModule(mongoDB *mongo.Database, vlServ service.IVisitLogService, csServ service2.ICountStatsService, posLikeModule *post_like.Module, commentModule *comment.Module) *Module {
	iPostLikeService := posLikeModule.Svc
	iCommentService := commentModule.Svc
	ipApiService := service3.NewIpApiService()
	dataAnalysisHandler := web.NewDataAnalysisHandler(vlServ, csServ, iPostLikeService, iCommentService, ipApiService)
	module := &Module{
		Hdl: dataAnalysisHandler,
	}
	return module
}

// wire.go:

var DataAnalysisProviders = wire.NewSet(web.NewDataAnalysisHandler, service3.NewIpApiService, wire.Bind(new(service3.IIpApiService), new(*service3.IpApiService)))
