// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package category

import (
	"github.com/chenmingyong0423/fnote/server/internal/category/internal/repository"
	"github.com/chenmingyong0423/fnote/server/internal/category/internal/repository/dao"
	"github.com/chenmingyong0423/fnote/server/internal/category/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/category/internal/web"
	"github.com/chenmingyong0423/go-eventbus"
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitCategoryModule(db *mongox.Database, eventBus *eventbus.EventBus) *Module {
	categoryDao := dao.NewCategoryDao(db)
	categoryRepository := repository.NewCategoryRepository(categoryDao)
	categoryService := service.NewCategoryService(categoryRepository, eventBus)
	categoryHandler := web.NewCategoryHandler(categoryService)
	module := &Module{
		Svc: categoryService,
		Hdl: categoryHandler,
	}
	return module
}

// wire.go:

var CategoryProviders = wire.NewSet(web.NewCategoryHandler, service.NewCategoryService, repository.NewCategoryRepository, dao.NewCategoryDao, wire.Bind(new(service.ICategoryService), new(*service.CategoryService)), wire.Bind(new(repository.ICategoryRepository), new(*repository.CategoryRepository)), wire.Bind(new(dao.ICategoryDao), new(*dao.CategoryDao)))
