// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tag

import (
	"github.com/chenmingyong0423/fnote/server/internal/tag/internal/repository"
	"github.com/chenmingyong0423/fnote/server/internal/tag/internal/repository/dao"
	"github.com/chenmingyong0423/fnote/server/internal/tag/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/tag/internal/web"
	"github.com/chenmingyong0423/go-eventbus"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitTagModule(mongoDB *mongo.Database, eventBus *eventbus.EventBus) *Module {
	tagDao := dao.NewTagDao(mongoDB)
	tagRepository := repository.NewTagRepository(tagDao)
	tagService := service.NewTagService(tagRepository, eventBus)
	tagHandler := web.NewTagHandler(tagService)
	module := &Module{
		Svc: tagService,
		Hdl: tagHandler,
	}
	return module
}

// wire.go:

var TagProviders = wire.NewSet(web.NewTagHandler, service.NewTagService, repository.NewTagRepository, dao.NewTagDao, wire.Bind(new(service.ITagService), new(*service.TagService)), wire.Bind(new(repository.ITagRepository), new(*repository.TagRepository)), wire.Bind(new(dao.ITagDao), new(*dao.TagDao)))
