// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package backup

import (
	"github.com/chenmingyong0423/fnote/server/internal/backup/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/backup/internal/web"
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitBackupModule(db *mongox.Database) *Module {
	backupService := service.NewBackupService(db)
	backupHandler := web.NewBackupHandler(backupService)
	module := &Module{
		Svc: backupService,
		Hdl: backupHandler,
	}
	return module
}

// wire.go:

var BackupProviders = wire.NewSet(web.NewBackupHandler, service.NewBackupService, wire.Bind(new(service.IBackupService), new(*service.BackupService)))
