# Nginx reverse proxy to front Next.js app
FROM nginx:1.27-alpine

ARG UPSTREAM_WEB=http://web:3000
ARG SERVER_NAME=localhost

ENV UPSTREAM_WEB=${UPSTREAM_WEB}
ENV SERVER_NAME=${SERVER_NAME}

COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

