// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post_visit

import (
	"github.com/chenmingyong0423/fnote/server/internal/post_visit/internal/repository"
	"github.com/chenmingyong0423/fnote/server/internal/post_visit/internal/repository/dao"
	"github.com/chenmingyong0423/fnote/server/internal/post_visit/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/post_visit/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitPostVisitModule(mongoDB *mongo.Database) *Module {
	postVisitDao := dao.NewPostVisitDao(mongoDB)
	postVisitRepository := repository.NewPostVisitRepository(postVisitDao)
	postVisitService := service.NewPostVisitService(postVisitRepository)
	postVisitHandler := web.NewPostVisitHandler(postVisitService)
	module := &Module{
		Svc: postVisitService,
		Hdl: postVisitHandler,
	}
	return module
}

// wire.go:

var PostVisitProviders = wire.NewSet(web.NewPostVisitHandler, service.NewPostVisitService, repository.NewPostVisitRepository, dao.NewPostVisitDao, wire.Bind(new(service.IPostVisitService), new(*service.PostVisitService)), wire.Bind(new(repository.IPostVisitRepository), new(*repository.PostVisitRepository)), wire.Bind(new(dao.IPostVisitDao), new(*dao.PostVisitDao)))
